// Content that is a rule, not a list.
//
// Some of the most-practiced K-12 material should never be typed by anybody,
// because it is generated by a rule: multiplication facts, number bonds, sight
// words. Asking a parent to paste four hundred multiplication facts is asking
// them not to bother.
//
// **This is the largest coverage gain per unit of work in the whole plan**, and
// it needs no importer, no enrichment and no adult. A generated bank is a
// `QuizDeck` as far as the rest of the app is concerned — same mastery keys,
// same schedule, same activities.
//
// Ids are derived from the parameters, exactly as `starterDecks.ts` derives
// them from position, and for the same reason: a learner's mastery is stored
// against `deckId:cardId`, so a random id on every page load would hand
// everyone a blank slate.

import type { QuizCard, QuizDeck } from './progress.js'

export type Operation = 'add' | 'subtract' | 'multiply' | 'divide'

export interface FactSpec {
  op: Operation
  /** Inclusive bounds for the operands. */
  min: number
  max: number
}

const SYMBOL: Record<Operation, string> = {
  add: '+',
  subtract: '−',
  multiply: '×',
  divide: '÷',
}

const OP_NAME: Record<Operation, string> = {
  add: 'Addition',
  subtract: 'Subtraction',
  multiply: 'Multiplication',
  divide: 'Division',
}

export function factDeckId(spec: FactSpec): string {
  return `gen-math-${spec.op}-${spec.min}-${spec.max}`
}

/**
 * How hard one fact is, on the same 1-5 scale as everything else.
 *
 * Not the size of the numbers alone: what actually makes a fact hard is whether
 * it carries or borrows, and whether it is one of the handful everybody finds
 * awkward. The times tables are not uniformly difficult — 7×8 is famously the
 * last one anybody learns, and 2×anything is nearly free.
 */
export function factDifficulty(op: Operation, a: number, b: number): number {
  let score = 1.4

  if (op === 'multiply' || op === 'divide') {
    // 0, 1, 2, 5 and 10 have rules a child can apply rather than recall.
    const easy = (n: number) => [0, 1, 2, 5, 10].includes(n)
    if (!easy(a) && !easy(b)) score += 1.4
    else if (!easy(a) || !easy(b)) score += 0.6
    if (Math.min(a, b) >= 6 && Math.max(a, b) >= 6) score += 0.8
  } else {
    const carries = op === 'add' ? (a % 10) + (b % 10) >= 10 : a % 10 < b % 10
    if (carries) score += 1.2
    if (Math.max(a, b) >= 10) score += 0.5
  }

  if (Math.max(a, b) >= 12) score += 0.4
  return Math.min(5, Math.max(1, Math.round(score * 10) / 10))
}

function factCard(op: Operation, a: number, b: number): QuizCard {
  const answer =
    op === 'add' ? a + b : op === 'subtract' ? a - b : op === 'multiply' ? a * b : a / b
  return {
    // Derived from the fact itself, so mastery survives everything.
    id: `${op}-${a}-${b}`,
    term: `${a} ${SYMBOL[op]} ${b}`,
    definition: String(answer),
    hint: null,
    difficulty: factDifficulty(op, a, b),
    // Grading a number by edit distance is nonsense: a transposition is a
    // wrong answer, not a typo.
    answerKind: 'numeric',
  }
}

/**
 * Every fact in the range.
 *
 * Subtraction and division are generated from their inverse so the answer is
 * always a whole number — there is no point asking a seven-year-old 7 ÷ 3.
 */
export function generateFacts(spec: FactSpec): QuizCard[] {
  const cards: QuizCard[] = []
  const lo = Math.min(spec.min, spec.max)
  const hi = Math.max(spec.min, spec.max)

  for (let a = lo; a <= hi; a++) {
    for (let b = lo; b <= hi; b++) {
      if (spec.op === 'subtract') {
        // a is the sum, b the part taken away, so the answer never goes below
        // zero — negatives are a different topic entirely.
        cards.push(factCard('subtract', a + b, b))
      } else if (spec.op === 'divide') {
        if (b === 0) continue
        cards.push(factCard('divide', a * b, b))
      } else {
        cards.push(factCard(spec.op, a, b))
      }
    }
  }

  // Two orderings of the same fact are the same fact to a learner meeting it,
  // and 3×4 twice in a round reads as a bug.
  const seen = new Set<string>()
  return cards.filter((c) => {
    if (seen.has(c.id)) return false
    seen.add(c.id)
    return true
  })
}

export function factDeck(spec: FactSpec): QuizDeck {
  const cards = generateFacts(spec)
  return {
    id: factDeckId(spec),
    track: 'math.facts',
    objectives: [],
    title: `${OP_NAME[spec.op]} to ${Math.max(spec.min, spec.max)}`,
    description: `Every ${OP_NAME[spec.op].toLowerCase()} fact from ${Math.min(spec.min, spec.max)} to ${Math.max(spec.min, spec.max)}.`,
    tags: ['math', 'facts'],
    cards,
    source: 'starter',
    termLabel: 'Fact',
    definitionLabel: 'Answer',
    createdAt: 0,
    updatedAt: 0,
  }
}

/** The banks worth offering out of the box, easiest first. */
export const FACT_BANKS: FactSpec[] = [
  { op: 'add', min: 0, max: 10 },
  { op: 'subtract', min: 0, max: 10 },
  { op: 'multiply', min: 0, max: 10 },
  { op: 'divide', min: 1, max: 10 },
  { op: 'add', min: 0, max: 20 },
  { op: 'multiply', min: 0, max: 12 },
]

export function generatedDecks(): QuizDeck[] {
  return FACT_BANKS.map(factDeck)
}
